// src/app/components/partials/form/form.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';

import { ApiService } from '../../../services/api.service';

import { LatLng } from 'leaflet';

@Component({
  selector: 'app-form',
  styleUrls: ['./form.component.scss'],
  templateUrl: './form.component.html',
})
export class FormComponent implements OnInit {
  @Input() public species: any[];
  @Input() public latlng: LatLng;
  @Output() public trees: EventEmitter<any[]> = new EventEmitter();
  public isCollapsed = true;
  public validated = false;
  public form: FormGroup;

  constructor(private apiService: ApiService) { }

  public ngOnInit(): void {
    this.form = new FormGroup({
      flavors: new FormControl(false),
      marker: new FormControl(''),
      origin: new FormControl(''),
      region: new FormControl([]),
      species: new FormControl(''),
    });
  }

  public search(): void {
    if (this.form.invalid) {
      this.validated = true;
      return;
    }

    const data = JSON.stringify(this.form.value);

    this.apiService.search(data).subscribe(
      (trees) => this.trees.emit(trees),
      (errors) => {
        if (errors) {
          this.validated = true;
        }
      },
    );
  }
}

<form [formGroup]="form" [ngClass]="{ 'was-validated': validated }" novalidate>
  <input type="hidden" name="user_latlng">
  <input type="hidden" name="radio" value="1000">
  <div class="row">
    <div class="col-12">
      <div class="form-group">
        <h2>
          ¿Dónde?
        </h2>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="marker-all" formControlName="marker" class="custom-control-input" value="0">
          <label class="custom-control-label" for="marker-all">
            En todo el mapa
          </label>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="marker-point" formControlName="marker" class="custom-control-input" [value]="latlng">
          <label class="custom-control-label" for="marker-point">
            Marcar en el mapa
          </label>
        </div>
      </div>
    </div>

    <div class="col-12">
      <div class="form-group">
        <h2>
          ¿Qué especie?
          <a href="#">
            <!-- <Icon :icon="['far', 'trash-alt']"> -->
          </a>
        </h2>
        <app-species-select [elements]="species" formControlName="species"></app-species-select>
      </div>
    </div>

    <div class="col-12" id="filters" [collapse]="isCollapsed" [isAnimated]="true">
      <div class="form-group">
        <h2>
          Sabores
        </h2>
        <div class="custom-control custom-switch">
          <input type="checkbox" class="custom-control-input" id="input-flavors" formControlName="flavors">
          <label class="custom-control-label" for="input-flavors">
            Frutales y medicinales
          </label>
        </div>
      </div>

      <div class="form-group">
        <h2>
          Origen
        </h2>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="rorigen-nativas" formControlName="origin" class="custom-control-input" value="Nativo/Autóctono">
          <label class="custom-control-label" for="rorigen-nativas">
            Nativas
          </label>
        </div>
        <div class="custom-control custom-radio custom-control-inline">
          <input type="radio" id="rorigen-exoticas" formControlName="origin" class="custom-control-input" value="Exótico">
          <label class="custom-control-label" for="rorigen-exoticas">
            Exóticas
          </label>
        </div>
        <a href="#" id="borrar_origen">
          <!-- <Icon :icon="['far', 'trash-alt']"> -->
        </a>
      </div>

      <div class="form-group">
        <div class="regiones">
          <h2>
            Región de origen
          </h2>
          <div class="custom-control custom-switch custom-control-inline">
            <input type="checkbox" class="custom-control-input" id="borigen_pampeana" formControlName="region" value="pampeana">
            <label class="custom-control-label" for="borigen_pampeana">
              Pampeana
            </label>
          </div>
          <div class="custom-control custom-switch custom-control-inline">
            <input type="checkbox" class="custom-control-input" id="borigen_nea" formControlName="region" value="nea">
            <label class="custom-control-label" for="borigen_nea">
              NEA
            </label>
          </div>
          <div class="custom-control custom-switch custom-control-inline">
            <input type="checkbox" class="custom-control-input" id="borigen_noa" formControlName="region" value="noa">
            <label class="custom-control-label" for="borigen_noa">
              NOA
            </label>
          </div>
          <div class="custom-control custom-switch custom-control-inline">
            <input type="checkbox" class="custom-control-input" id="borigen_cuyana" formControlName="region" value="cuyana">
            <label class="custom-control-label" for="borigen_cuyana">
              Cuyana
            </label>
          </div>
          <div class="custom-control custom-switch custom-control-inline">
            <input type="checkbox" class="custom-control-input" id="borigen_patagonica" formControlName="region" value="patagonica">
            <label class="custom-control-label" for="borigen_patagonica">
              Patagónica
            </label>
          </div>
        </div>
      </div>
    </div>
    <div class="col-12">
      <button type="button" class="btn btn-secondary" (click)="isCollapsed = !isCollapsed" [attr.aria-expanded]="!isCollapsed" aria-controls="filters">
        <span *ngIf="!isCollapsed">Ocultar</span>
        <span *ngIf="isCollapsed">Mostrar</span>
        filtros
      </button>
    </div>
  </div>
  <button type="button" class="btn btn-primary btn-lg btn-block mt-4" (click)="search()">
    Buscar
  </button>
</form>

// src/components/Form.vue
<template>
  <form method="post">
    <input type="hidden" name="user_latlng" id="user_latlng" />
    <input type="hidden" name="radio" value="1000" />
    <div class="row">
      <div class="col-12">
        <div class="form-group">
          <h2>
            ¿Dónde?
          </h2>
          <div class="custom-control custom-radio custom-control-inline">
            <input
              type="radio"
              id="rdonde-ciudad"
              name="rdonde"
              class="custom-control-input"
              value="0"
            />
            <label class="custom-control-label" for="rdonde-ciudad">
              En todo el mapa
            </label>
          </div>
          <div class="custom-control custom-radio custom-control-inline">
            <input
              type="radio"
              id="rdonde-mapa"
              name="rdonde"
              class="custom-control-input"
              value="1"
            />
            <label class="custom-control-label" for="rdonde-mapa">
              Marcar en el mapa
            </label>
          </div>
        </div>
      </div>

      <div class="col-12">
        <div class="form-group">
          <h2>
            ¿Qué especie?
            <a href="#" id="borrar_especie_id">
              <Icon  :icon="['far', 'trash-alt']" />
            </a>
          </h2>
          <select class="custom-select" name="especie_id">
            <!-- Options loaded via ajax -->
          </select>
        </div>
      </div>

      <b-collapse class="col-12" id="filters">
        <div class="form-group">
          <h2>
            Sabores
          </h2>
          <div class="custom-control custom-switch">
            <input
              type="checkbox"
              class="custom-control-input"
              id="user_sabores"
              name="user_sabores"
            />
            <label class="custom-control-label" for="user_sabores">
              Frutales y medicinales
            </label>
          </div>
        </div>

        <div class="form-group">
          <h2>
            Origen
          </h2>
          <div class="custom-control custom-radio custom-control-inline">
            <input
              type="radio"
              id="rorigen-nativas"
              name="user_origen"
              class="custom-control-input"
              value="Nativo/Autóctono"
            />
            <label class="custom-control-label" for="rorigen-nativas">
              Nativas
            </label>
          </div>
          <div class="custom-control custom-radio custom-control-inline">
            <input
              type="radio"
              id="rorigen-exoticas"
              name="user_origen"
              class="custom-control-input"
              value="Exótico"
            />
            <label class="custom-control-label" for="rorigen-exoticas">
              Exóticas
            </label>
          </div>
          <a href="#" id="borrar_origen">
            <Icon  :icon="['far', 'trash-alt']" />
          </a>
        </div>

        <div class="form-group">
          <div class="regiones">
            <h2>
              Región de origen
            </h2>
            <div class="custom-control custom-switch custom-control-inline">
              <input
                type="checkbox"
                class="custom-control-input"
                id="borigen_pampeana"
                name="borigen_pampeana"
              />
              <label class="custom-control-label" for="borigen_pampeana">
                Pampeana
              </label>
            </div>
            <div class="custom-control custom-switch custom-control-inline">
              <input
                type="checkbox"
                class="custom-control-input"
                id="borigen_nea"
                name="borigen_nea"
              />
              <label class="custom-control-label" for="borigen_nea">
                NEA
              </label>
            </div>
            <div class="custom-control custom-switch custom-control-inline">
              <input
                type="checkbox"
                class="custom-control-input"
                id="borigen_noa"
                name="borigen_noa"
              />
              <label class="custom-control-label" for="borigen_noa">
                NOA
              </label>
            </div>
            <div class="custom-control custom-switch custom-control-inline">
              <input
                type="checkbox"
                class="custom-control-input"
                id="borigen_cuyana"
                name="borigen_cuyana"
              />
              <label class="custom-control-label" for="borigen_cuyana">
                Cuyana
              </label>
            </div>
            <div class="custom-control custom-switch custom-control-inline">
              <input
                type="checkbox"
                class="custom-control-input"
                id="borigen_patagonica"
                name="borigen_patagonica"
              />
              <label class="custom-control-label" for="borigen_patagonica">
                Patagónica
              </label>
            </div>
          </div>
        </div>
      </b-collapse>
      <div class="col-12">
        <button v-b-toggle.filters type="button" class="btn btn-secondary">
          Ocultar filtros
        </button>
      </div>
    </div>
    <input
      name="Buscar"
      type="submit"
      value="Buscar"
      class="btn btn-primary btn-lg btn-block mt-4"
    />
  </form>
</template>

<script>
export default {
  name: "Form"
};
</script>
